version: "3.7"
services:
  mongo:
    container_name: saturnmongo
    image: mongo
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: dev
      MONGO_INITDB_DATABASE: saturnreport
      MONGO_USERNAME: admin
      MONGO_PASSWORD: example
    ports:
      - 5001:27017
    volumes:
      - ./scripts/mongo-entrypoint.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    command: mongod
  mongo-express:
    container_name: saturnmongoadmin
    image: mongo-express
    restart: always
    ports:
      - 27018:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: dev